### ISSUE TITLE
Add debian package support to upstream

### ISSUE THREAD

**Issue by iomartin** [Mellanox/spdk#60]
I came here after looking for debian packaging support on upstream SPDK.

There was a discussion on the slack channel and they mentioned interest in getting this upstream: [link](https://spdk-team.slack.com/archives/CJE4C98G1/p1668025512971829)

Would there be interest from Mellanox into getting this upstream? I'd be happy to help with development, testing, etc.

**Comment by sbates130272** [comment]
I suspect it makes more sense for @iomartin to submit something to upstream SPDK so everyone can benefit from it.

**Comment by EugeneKochetov** [comment]
It will require a big effort for us to make our packaging scripts useful for both, Nvidia and community. Packaging process should be highly configurable in this case. And even then, no guarantee it will fit for us without additional patching.
So, currently we don't have plans to work on upstreaming of it.

**Comment by iomartin** [comment]
Thanks @EugeneKochetov, I will work something else and submit upstream
